version: "2"

# !!! USE LATEST RELEASE OF GOLANGCI-LINT (2.6.2) !!!

run:
  relative-path-mode: gomod
  timeout: 3m
  allow-parallel-runners: true

  # ----------------------------------------------------- LINTERS ------------------------------------------------------
linters:
  # [https://golangci-lint.run/docs/linters/]
  disable-all: true
  enable:
    - staticcheck # находит баги и проблемы производительности
    - unused # находит неиспользуемый код
    - govet # официальный инструмент Go для поиска подозрительных конструкций
    - revive # стилистические проверки кода
    - errcheck # проверяет обработку всех ошибок
    - ineffassign # находит неэффективные присваивания
    - noctx # проверяет передачу context в http.Request
    - errname # проверяет именование переменных ошибок
    - errorlint # проверяет правильную работу с wrapping/unwrapping ошибок
    - containedctx # запрещает хранить context в структурах
    - forcetypeassert # требует проверки type assertion
    - nilerr # находит возврат nil вместо ошибки
    - nilnil # запрещает одновременный возврат nil, nil
    - nilnesserr # проверяет сравнение ошибок с nil
    - contextcheck # проверяет правильную передачу context
    - rowserrcheck # проверяет закрытие sql.Rows
    - gocritic # мета-линтер с множеством проверок
    - bodyclose # проверяет закрытие http.Response.Body
    - sqlclosecheck # проверяет закрытие sql rows/statements
    - loggercheck # проверяет правильное использование логгеров
    - iotamixing # предотвращает смешивание iota с другими значениями
    - inamedparam # проверяет именование параметров в интерфейсах
    - makezero # находит некорректное использование make с append
    - musttag # требует теги для структур (json, yaml и т.д.)
    - modernize # заставляет использовать актуальные подходы
    - importas # проверяет алиасы импортов
    - canonicalheader # проверяет канонические заголовки HTTP
    - tparallel # проверяет правильное использование t.Parallel()
    - decorder # проверяет порядок объявлений в коде
    - embeddedstructfieldcheck # находит проблемы с embedded полями
    - thelper # проверяет правильное использование t.Helper()
    - durationcheck # проверяет умножение time.Duration
    - testifylint # улучшения для библиотеки testify
    - testableexamples # проверяет корректность Example функций
    - gosec # проверка безопасности кода
    - dupl # находит дублирование кода
    - cyclop # проверяет цикломатическую сложность
    - gocognit # проверяет когнитивную сложность
    - nestif # проверяет глубину вложенности if
    - wsl_v5 # проверяет пустые строки и форматирование
    - prealloc # рекомендует преаллокацию слайсов
    - perfsprint # оптимизация Sprint*/Sprintf
    - goprintffuncname # проверяет именование функций с Printf
    - mirror # находит зеркальные импорты
    - intrange # проверяет использование range для int
    - copyloopvar # предотвращает проблемы с захватом переменных цикла
    - iface # находит неиспользуемые интерфейсы
    - nosprintfhostport # запрещает sprintf для host:port
    - goconst # находит повторяющиеся строки для вынесения в константы
    - tagliatelle # проверяет стиль тегов структур
    - forbidigo # запрещает определенные вызовы функций
    - gochecknoglobals # запрещает глобальные переменные
    - gochecknoinits # запрещает init функции
    - asasalint # проверяет pass by value vs pointer
    - dogsled # находит множественные пустые идентификаторы (_)
    - bidichk # проверяет опасные unicode символы
    - gomodguard # контролирует разрешенные зависимости
    - mnd # находит magic numbers
    - nakedret # запрещает голые return в длинных функциях
    - promlinter # проверяет метрики Prometheus
    - reassign # находит переприсваивание переменных
    - unconvert # находит ненужные конвертации типов
    - unparam # находит неиспользуемые параметры функций
    - funcorder # проверяет порядок функций
    - exptostd # рекомендует stdlib вместо экспериментальных пакетов
    - fatcontext # находит вложенные context с Value
    - usestdlibvars # рекомендует константы из stdlib
    - usetesting # рекомендует использовать testing.TB
    - recvcheck # проверяет консистентность receiver в методах
    - wastedassign # находит бесполезные присваивания
    #    - misspell  # отключен: автофикс ломает код (меняет названия переменных и т.д.)
    #    - wrapcheck # очень много рефачить
    #    - interfacebloat # ограничивает количество методов в интерфейсе
    #    - ireturn # возвращать конкретный тип, а не интерфейс + var _ Doer = (*IDoer)(nil) // TODO: использовать
    #    - testpackage # для тестов отдельный package *_test
    #    - funlen # ограничение длины функций
    #    - maintidx # индекс поддерживаемости функций
    #    - nolintlint # поиск //nolint: и удаление
  # ---------------------------------------------------- EXCLUSIONS ----------------------------------------------------
  exclusions:
    generated: lax
    # [https://golangci-lint.run/docs/linters/false-positives/]
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules: # один из примеров использования:
      # - path: /
      #  text: "cognitive complexity"
      #  отключает все ошибки с текстом "cognitive complexity"
      #  можно добавить опцию
      #  linters:
      #    - gocognit
      - path: /
        text: "ALL_CAPS"
        linters:
          - revive
      - path: /
        text: "URL"
        linters:
          - revive
      - path: /
        text: "ID"
        linters:
          - revive
      - path: /
        text: "_id"
        linters:
          - tagliatelle
    paths:
      - third_party$
      - builtin$
      - examples$

  # ----------------------------------------------------- SETTINGS -----------------------------------------------------
  settings:
    dupl:
      threshold: 100
    cyclop:
      max-complexity: 15
      package-average: 12
    govet:
      enable-all: true
    tagliatelle:
      case:
        rules:
          # TODO: согласовать единый вид
          yaml: snake
          json: snake
          bson: snake
          xml: pascal
        ignored-fields:
          - ID
    mnd:
      checks:
        - argument
        - case
        - condition
        - operation
        - return
      ignored-numbers:
        - "0"
        - "1"
        - "2"
        - "3"
        - "4"
        - "5"
        - "10"
        - "16"
        - "24"
        - "32"
        - "60"
        - "64"
        - "100"
        - "128"
        - "200"
        - "256"
        - "400"
        - "401"
        - "403"
        - "404"
        - "409"
        - "500"
        - "512"
        - "1000"
        - "1024"
        - "2048"
        - "4096"
        - "8192"
      ignored-functions:
        - "time.Sleep"
        - "strconv.FormatInt"
        - "strconv.FormatUint"
        - "strconv.Itoa"

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  # It's not practical to fix all existing issues at the moment of integration:
  # much better don't allow issues in new code.
  # [https://golangci-lint.run/docs/configuration/file/#run-configuration]
  new: false # позволяет проверять только unstaged changes
  fix: false # auto-fix, отключено, так как даже авто фикс должен быть под присмотром человека

# ----------------------------------------------------- FORMATTERS -----------------------------------------------------
formatters:
  enable:
    - gofumpt
    - golines
    - gci
  settings:
    gofumpt:
      extra-rules: true # добавляет автофикс paramTypeCombine
    golines:
      max-len: 120
      tab-len: 1
      reformat-tags: false
      shorten-comments: false
  exclusions:
    generated: lax
    paths:
      - vendor/
      - ".*/vendor/.*"
      - "vendor/.*"
      - third_party/
      - ".*/third_party/.*"
      - docs/